name: hadirin_staff_app
description: Hadir-In Staff Attendance App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  intl: ^0.18.1
  intl_utils: ^2.8.5
  shared_preferences: ^2.2.0
  percent_indicator: ^4.2.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo_hadir_in.png
    - assets/images/logo_hadir_in_dengan_tulisan.png
    - assets/images/maskot_hadir_in.png
    - assets/images/maskot_hadir_in_melambai.png